steps:
- id: Build
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'northamerica-northeast2-docker.pkg.dev/echobot-486304/echobot-repo/echobot:$SHORT_SHA', './services/echobot']
- id: Push
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'northamerica-northeast2-docker.pkg.dev/echobot-486304/echobot-repo/echobot:$SHORT_SHA']
- id: Deploy
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: gcloud
  args:
  - run
  - deploy
  - echobot
  - --image=northamerica-northeast2-docker.pkg.dev/echobot-486304/echobot-repo/echobot:$SHORT_SHA
  - --region=northamerica-northeast2
  - --platform=managed
  - --service-account=echo-deployer@echobot-486304.iam.gserviceaccount.com
  - --set-secrets=SLACK_BOT_TOKEN=projects/914835758459/secrets/slack-bot-token:latest,SLACK_SIGNING_SECRET=projects/914835758459/secrets/slack-signing-secret:latest
  - --min-instances=1
  - --memory=512Mi
  - --concurrency=80
options:
  logging: CLOUD_LOGGING_ONLY
images:
- 'northamerica-northeast2.pkg.dev/echobot-486304/echobot-repo/echobot:$SHORT_SHA'
substitutions:
  _REGION: "northamerica-northeast2"
timeout: '1200s'
